// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AccordionitemDocumentDataSlicesSlice =
  | ButtonSliceSlice
  | EmbedSliceSlice
  | ImageSliceSlice
  | TextSliceSlice;

/**
 * Content for AccordionItem documents
 */
interface AccordionitemDocumentData {
  /**
   * Title field in *AccordionItem*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accordionitem.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *AccordionItem*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: accordionitem.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AccordionitemDocumentDataSlicesSlice>;
}

/**
 * AccordionItem document from Prismic
 *
 * - **API ID**: `accordionitem`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AccordionitemDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AccordionitemDocumentData>,
    "accordionitem",
    Lang
  >;

type BankpageDocumentDataSlicesSlice = never;

/**
 * Content for BankPage documents
 */
interface BankpageDocumentData {
  /**
   * Headline field in *BankPage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bankpage.headline
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  headline: prismic.RichTextField;

  /**
   * Description1 field in *BankPage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bankpage.description1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description1: prismic.RichTextField;

  /**
   * Description2 field in *BankPage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bankpage.description2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description2: prismic.RichTextField;

  /**
   * Description3 field in *BankPage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bankpage.description3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description3: prismic.RichTextField;

  /**
   * SEO Title field in *BankPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bankpage.seo_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_title: prismic.KeyTextField;

  /**
   * SEO Description field in *BankPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bankpage.seo_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_description: prismic.KeyTextField;

  /**
   * Custom Subtitle field in *BankPage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bankpage.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * Slice Zone field in *BankPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: bankpage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BankpageDocumentDataSlicesSlice>;
}

/**
 * BankPage document from Prismic
 *
 * - **API ID**: `bankpage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BankpageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BankpageDocumentData>,
    "bankpage",
    Lang
  >;

type BlogpostDocumentDataSlicesSlice =
  | TextSliceSlice
  | EmbedSliceSlice
  | ImageSliceSlice
  | AccordionSliceSlice;

/**
 * Content for BlogPost documents
 */
interface BlogpostDocumentData {
  /**
   * Title field in *BlogPost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Author field in *BlogPost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField;

  /**
   * PublicationDate field in *BlogPost*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.publicationdate
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  publicationdate: prismic.DateField;

  /**
   * Description field in *BlogPost*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * CardImage (optional) field in *BlogPost*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.cardimage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cardimage: prismic.ImageField<never>;

  /**
   * Slice Zone field in *BlogPost*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogpostDocumentDataSlicesSlice>;
}

/**
 * BlogPost document from Prismic
 *
 * - **API ID**: `blogpost`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogpostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogpostDocumentData>,
    "blogpost",
    Lang
  >;

/**
 * Content for CallToAction documents
 */
interface CalltoactionDocumentData {
  /**
   * Title field in *CallToAction*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: calltoaction.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *CallToAction*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: calltoaction.text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * checklist1 field in *CallToAction*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: calltoaction.checklist1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  checklist1: prismic.RichTextField;

  /**
   * checklist2 field in *CallToAction*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: calltoaction.checklist2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  checklist2: prismic.RichTextField;

  /**
   * checklist3 field in *CallToAction*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: calltoaction.checklist3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  checklist3: prismic.RichTextField;
}

/**
 * CallToAction document from Prismic
 *
 * - **API ID**: `calltoaction`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CalltoactionDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<CalltoactionDocumentData>,
    "calltoaction",
    Lang
  >;

type CertificationpageDocumentDataSlicesSlice =
  | AccordionSliceSlice
  | EmbedSliceSlice
  | ButtonSliceSlice
  | ImageSliceSlice
  | TextSliceSlice;

/**
 * Content for CertificationPage documents
 */
interface CertificationpageDocumentData {
  /**
   * SEO Title field in *CertificationPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: certificationpage.seo_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_title: prismic.KeyTextField;

  /**
   * SEO Description field in *CertificationPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: certificationpage.seo_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_description: prismic.KeyTextField;

  /**
   * Slice Zone field in *CertificationPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: certificationpage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CertificationpageDocumentDataSlicesSlice>;
}

/**
 * CertificationPage document from Prismic
 *
 * - **API ID**: `certificationpage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CertificationpageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<CertificationpageDocumentData>,
    "certificationpage",
    Lang
  >;

/**
 * Content for ContactPage documents
 */
interface ContactpageDocumentData {
  /**
   * Description field in *ContactPage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contactpage.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * SEO Title field in *ContactPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contactpage.seo_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_title: prismic.KeyTextField;

  /**
   * SEO Description field in *ContactPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contactpage.seo_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_description: prismic.KeyTextField;
}

/**
 * ContactPage document from Prismic
 *
 * - **API ID**: `contactpage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactpageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactpageDocumentData>,
    "contactpage",
    Lang
  >;

type DisclaimerpageDocumentDataSlicesSlice = TextSliceSlice;

/**
 * Content for DisclaimerPage documents
 */
interface DisclaimerpageDocumentData {
  /**
   * SEO Title field in *DisclaimerPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: disclaimerpage.seo_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_title: prismic.KeyTextField;

  /**
   * SEO Description field in *DisclaimerPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: disclaimerpage.seo_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_description: prismic.KeyTextField;

  /**
   * Slice Zone field in *DisclaimerPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: disclaimerpage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<DisclaimerpageDocumentDataSlicesSlice>;
}

/**
 * DisclaimerPage document from Prismic
 *
 * - **API ID**: `disclaimerpage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DisclaimerpageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<DisclaimerpageDocumentData>,
    "disclaimerpage",
    Lang
  >;

/**
 * Content for DonationPage documents
 */
interface DonationpageDocumentData {
  /**
   * Title field in *DonationPage*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: donationpage.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *DonationPage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: donationpage.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Photo field in *DonationPage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: donationpage.photo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  photo: prismic.ImageField<never>;

  /**
   * Donation-title field in *DonationPage*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: donationpage.donation-title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  "donation-title": prismic.TitleField;

  /**
   * Donation-description field in *DonationPage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: donationpage.donation-description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  "donation-description": prismic.RichTextField;

  /**
   * Donation-button field in *DonationPage*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: donationpage.donation-button
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  "donation-button": prismic.TitleField;

  /**
   * seo_title field in *DonationPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: donationpage.seo_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_title: prismic.KeyTextField;

  /**
   * seo_description field in *DonationPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: donationpage.seo_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_description: prismic.KeyTextField;
}

/**
 * DonationPage document from Prismic
 *
 * - **API ID**: `donationpage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DonationpageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<DonationpageDocumentData>,
    "donationpage",
    Lang
  >;

type EcobankspageDocumentDataSlicesSlice = AccordionSliceSlice | TextSliceSlice;

type EcobankspageDocumentDataSlices1Slice =
  | AccordionSliceSlice
  | TextSliceSlice;

/**
 * Content for EcoBanksPage documents
 */
interface EcobankspageDocumentData {
  /**
   * SEO Title field in *EcoBanksPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ecobankspage.seo_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_title: prismic.KeyTextField;

  /**
   * SEO Description field in *EcoBanksPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ecobankspage.seo_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_description: prismic.KeyTextField;

  /**
   * Slice Zone field in *EcoBanksPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: ecobankspage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<EcobankspageDocumentDataSlicesSlice>
  /**
   * Slice Zone field in *EcoBanksPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: ecobankspage.slices1[]
   * - **Tab**: FAQ
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices1: prismic.SliceZone<EcobankspageDocumentDataSlices1Slice>;
}

/**
 * EcoBanksPage document from Prismic
 *
 * - **API ID**: `ecobankspage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EcobankspageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<EcobankspageDocumentData>,
    "ecobankspage",
    Lang
  >;

/**
 * Content for EmbracePage documents
 */
interface EmbracepageDocumentData {
  /**
   * Title field in *EmbracePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: embracepage.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * SubTitle field in *EmbracePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: embracepage.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Description1 field in *EmbracePage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: embracepage.description1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description1: prismic.RichTextField;

  /**
   * Description2 field in *EmbracePage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: embracepage.description2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description2: prismic.RichTextField;

  /**
   * SEO Title field in *EmbracePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: embracepage.seo_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_title: prismic.KeyTextField;

  /**
   * SEO Description field in *EmbracePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: embracepage.seo_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_description: prismic.KeyTextField
  /**
   * Preview Title field in *EmbracePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: embracepage.preview_title
   * - **Tab**: Preview
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  preview_title: prismic.KeyTextField;

  /**
   * Preview Description field in *EmbracePage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: embracepage.preview_description
   * - **Tab**: Preview
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  preview_description: prismic.RichTextField;

  /**
   * Preview Area Label field in *EmbracePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: embracepage.preview_area_label
   * - **Tab**: Preview
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  preview_area_label: prismic.KeyTextField;

  /**
   * Copy Text Button Label field in *EmbracePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: embracepage.copy_text_button_label
   * - **Tab**: Preview
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  copy_text_button_label: prismic.KeyTextField;

  /**
   * Preview Footnote field in *EmbracePage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: embracepage.preview_footnote
   * - **Tab**: Preview
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  preview_footnote: prismic.RichTextField;

  /**
   * cancel_button_label field in *EmbracePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: embracepage.cancel_button_label
   * - **Tab**: Preview
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cancel_button_label: prismic.KeyTextField;

  /**
   * Proceed Button Label field in *EmbracePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: embracepage.proceed_button_label
   * - **Tab**: Preview
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  proceed_button_label: prismic.KeyTextField
  /**
   * Form Title field in *EmbracePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: embracepage.form_title
   * - **Tab**: Form
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  form_title: prismic.KeyTextField;

  /**
   * Full Name Label field in *EmbracePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: embracepage.full_name_label
   * - **Tab**: Form
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  full_name_label: prismic.KeyTextField;

  /**
   * Full Name Placeholder field in *EmbracePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: embracepage.full_name_placeholder
   * - **Tab**: Form
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  full_name_placeholder: prismic.KeyTextField;

  /**
   * Full Name Warning field in *EmbracePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: embracepage.full_name_warning
   * - **Tab**: Form
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  full_name_warning: prismic.KeyTextField;

  /**
   * Bank Select_label field in *EmbracePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: embracepage.bank_select_label
   * - **Tab**: Form
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bank_select_label: prismic.KeyTextField;

  /**
   * Bank Select Info field in *EmbracePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: embracepage.bank_select_info
   * - **Tab**: Form
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bank_select_info: prismic.KeyTextField;

  /**
   * Bank Not Found field in *EmbracePage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: embracepage.bank_not_found
   * - **Tab**: Form
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bank_not_found: prismic.RichTextField;

  /**
   * Email Label field in *EmbracePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: embracepage.email_label
   * - **Tab**: Form
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email_label: prismic.KeyTextField;

  /**
   * Email Placeholder field in *EmbracePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: embracepage.email_placeholder
   * - **Tab**: Form
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email_placeholder: prismic.KeyTextField;

  /**
   * Hometown Label field in *EmbracePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: embracepage.hometown_label
   * - **Tab**: Form
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hometown_label: prismic.KeyTextField;

  /**
   * Hometown_placeholder field in *EmbracePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: embracepage.hometown_placeholder
   * - **Tab**: Form
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hometown_placeholder: prismic.KeyTextField;

  /**
   * Background Label field in *EmbracePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: embracepage.background_label
   * - **Tab**: Form
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  background_label: prismic.KeyTextField;

  /**
   * Background Placeholder field in *EmbracePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: embracepage.background_placeholder
   * - **Tab**: Form
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  background_placeholder: prismic.KeyTextField;

  /**
   * Why Embrace Label field in *EmbracePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: embracepage.why_embrace_label
   * - **Tab**: Form
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  why_embrace_label: prismic.KeyTextField;

  /**
   * Why Embrace Placeholder field in *EmbracePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: embracepage.why_embrace_placeholder
   * - **Tab**: Form
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  why_embrace_placeholder: prismic.KeyTextField;

  /**
   * Marketing Checkbox Label field in *EmbracePage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: embracepage.marketing_checkbox_label
   * - **Tab**: Form
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  marketing_checkbox_label: prismic.RichTextField;

  /**
   * Privacy Checkbox Label field in *EmbracePage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: embracepage.privacy_checkbox_label
   * - **Tab**: Form
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  privacy_checkbox_label: prismic.RichTextField;

  /**
   * Privacy Policy Link Text field in *EmbracePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: embracepage.privacy_policy_link_text
   * - **Tab**: Form
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  privacy_policy_link_text: prismic.KeyTextField;
}

/**
 * EmbracePage document from Prismic
 *
 * - **API ID**: `embracepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EmbracepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<EmbracepageDocumentData>,
    "embracepage",
    Lang
  >;

type FaqpageDocumentDataSlicesSlice = AccordionSliceSlice;

/**
 * Content for FAQPage documents
 */
interface FaqpageDocumentData {
  /**
   * Introduction field in *FAQPage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqpage.introduction
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  introduction: prismic.RichTextField;

  /**
   * SEO Title field in *FAQPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqpage.seo_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_title: prismic.KeyTextField;

  /**
   * SEO Description field in *FAQPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqpage.seo_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_description: prismic.KeyTextField;

  /**
   * Slice Zone field in *FAQPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: faqpage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FaqpageDocumentDataSlicesSlice>;
}

/**
 * FAQPage document from Prismic
 *
 * - **API ID**: `faqpage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FaqpageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FaqpageDocumentData>,
    "faqpage",
    Lang
  >;

type HomepageDocumentDataSlices1Slice = FeaturedInSliceSlice;

/**
 * Content for HomePage documents
 */
interface HomepageDocumentData {
  /**
   * Description1 field in *HomePage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.description1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description1: prismic.RichTextField;

  /**
   * Description2 field in *HomePage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.description2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description2: prismic.RichTextField;

  /**
   * Description3 field in *HomePage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.description3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description3: prismic.RichTextField;

  /**
   * Description4 field in *HomePage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.description4
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description4: prismic.RichTextField;

  /**
   * SEO Title field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.seo_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_title: prismic.KeyTextField;

  /**
   * SEO Description field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.seo_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_description: prismic.KeyTextField
  /**
   * Slice Zone field in *HomePage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices1[]
   * - **Tab**: As Featured In
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices1: prismic.SliceZone<HomepageDocumentDataSlices1Slice>;
}

/**
 * HomePage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Content for PledgePage documents
 */
interface PledgepageDocumentData {
  /**
   * Introduction field in *PledgePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pledgepage.introduction
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  introduction: prismic.KeyTextField;

  /**
   * Description 1 field in *PledgePage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pledgepage.description1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description1: prismic.RichTextField;

  /**
   * Description 2 field in *PledgePage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pledgepage.description2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description2: prismic.RichTextField;

  /**
   * SEO Title field in *PledgePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pledgepage.seo_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_title: prismic.KeyTextField;

  /**
   * SEO Description field in *PledgePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pledgepage.seo_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_description: prismic.KeyTextField;
}

/**
 * PledgePage document from Prismic
 *
 * - **API ID**: `pledgepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PledgepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PledgepageDocumentData>,
    "pledgepage",
    Lang
  >;

type PresspageDocumentDataSlicesSlice = TextSliceSlice;

/**
 * Content for PressPage documents
 */
interface PresspageDocumentData {
  /**
   * SEO Title field in *PressPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: presspage.seo_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_title: prismic.KeyTextField;

  /**
   * SEO Description field in *PressPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: presspage.seo_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_description: prismic.KeyTextField;

  /**
   * Slice Zone field in *PressPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: presspage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PresspageDocumentDataSlicesSlice>;
}

/**
 * PressPage document from Prismic
 *
 * - **API ID**: `presspage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PresspageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PresspageDocumentData>,
    "presspage",
    Lang
  >;

type PresspostDocumentDataSlicesSlice =
  | TextSliceSlice
  | ImageSliceSlice
  | EmbedSliceSlice;

/**
 * Content for PressPost documents
 */
interface PresspostDocumentData {
  /**
   * Title field in *PressPost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: presspost.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Author field in *PressPost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: presspost.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField;

  /**
   * Email field in *PressPost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: presspost.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Phone field in *PressPost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: presspost.phone
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone: prismic.KeyTextField;

  /**
   * ReleaseDate field in *PressPost*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: presspost.releasedate
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  releasedate: prismic.DateField;

  /**
   * Description field in *PressPost*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: presspost.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Slice Zone field in *PressPost*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: presspost.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PresspostDocumentDataSlicesSlice>;
}

/**
 * PressPost document from Prismic
 *
 * - **API ID**: `presspost`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PresspostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PresspostDocumentData>,
    "presspost",
    Lang
  >;

type PrivacypageDocumentDataSlicesSlice = TextSliceSlice;

/**
 * Content for PrivacyPage documents
 */
interface PrivacypageDocumentData {
  /**
   * SEO Title field in *PrivacyPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: privacypage.seo_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_title: prismic.KeyTextField;

  /**
   * SEO Description field in *PrivacyPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: privacypage.seo_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_description: prismic.KeyTextField;

  /**
   * Slice Zone field in *PrivacyPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: privacypage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PrivacypageDocumentDataSlicesSlice>;
}

/**
 * PrivacyPage document from Prismic
 *
 * - **API ID**: `privacypage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PrivacypageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PrivacypageDocumentData>,
    "privacypage",
    Lang
  >;

/**
 * Content for SFIDefaults documents
 */
interface SfiPageDocumentData {
  /**
   * switch-survey-text field in *SFIDefaults*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Have you opened an account with {{bank name}} since visiting Bank Green?
   * - **API ID Path**: sfi-page.switch-survey-text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  "switch-survey-text": prismic.RichTextField;

  /**
   * switch-survey-link field in *SFIDefaults*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: please let us know
   * - **API ID Path**: sfi-page.switch-survey-link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  "switch-survey-link": prismic.RichTextField;

  /**
   * impact-image field in *SFIDefaults*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sfi-page.impact-image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  "impact-image": prismic.ImageField<never>;

  /**
   * security-image field in *SFIDefaults*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sfi-page.security-image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  "security-image": prismic.ImageField<never>;

  /**
   * service-image field in *SFIDefaults*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sfi-page.service-image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  "service-image": prismic.ImageField<never>;

  /**
   * convenience-image field in *SFIDefaults*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sfi-page.convenience-image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  "convenience-image": prismic.ImageField<never>;

  /**
   * institution_credentials-bankers for net zero field in *SFIDefaults*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sfi-page.institution_credentials-bankers_for_net_zero
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  "institution_credentials-bankers_for_net_zero": prismic.ImageField<never>;

  /**
   * institution_credentials-gabv field in *SFIDefaults*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sfi-page.institution_credentials-gabv
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  "institution_credentials-gabv": prismic.ImageField<never>;

  /**
   * institution_credentials-b impact field in *SFIDefaults*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sfi-page.institution_credentials-b_impact
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  "institution_credentials-b_impact": prismic.ImageField<never>;
}

/**
 * SFIDefaults document from Prismic
 *
 * - **API ID**: `sfi-page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SfiPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SfiPageDocumentData>,
    "sfi-page",
    Lang
  >;

/**
 * Content for SFIPage documents
 */
interface SfipageDocumentData {
  /**
   * Impact field in *SFIPage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sfipage.impact
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  impact: prismic.RichTextField;

  /**
   * Security field in *SFIPage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sfipage.security
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  security: prismic.RichTextField;

  /**
   * Services field in *SFIPage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sfipage.services
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  services: prismic.RichTextField;

  /**
   * Convenience field in *SFIPage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sfipage.convenience
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  convenience: prismic.RichTextField;

  /**
   * Founded field in *SFIPage*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: sfipage.founded
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  founded: prismic.NumberField;

  /**
   * our take field in *SFIPage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sfipage.our_take
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  our_take: prismic.RichTextField;

  /**
   * serving field in *SFIPage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sfipage.serving
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  serving: prismic.RichTextField;
}

/**
 * SFIPage document from Prismic
 *
 * - **API ID**: `sfipage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SfipageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SfipageDocumentData>,
    "sfipage",
    Lang
  >;

/**
 * Content for SwitchSurveyExit documents
 */
interface SwitchsurveyexitDocumentData {
  /**
   * title field in *SwitchSurveyExit*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: switchsurveyexit.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * subtitle field in *SwitchSurveyExit*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: switchsurveyexit.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * buttontext field in *SwitchSurveyExit*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: switchsurveyexit.buttontext
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  buttontext: prismic.RichTextField;

  /**
   * link field in *SwitchSurveyExit*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: switchsurveyexit.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * SwitchSurveyExit document from Prismic
 *
 * - **API ID**: `switchsurveyexit`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SwitchsurveyexitDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SwitchsurveyexitDocumentData>,
    "switchsurveyexit",
    Lang
  >;

type TakeactionpageDocumentDataSlices1Slice =
  | EmbedSliceSlice
  | ImageSliceSlice
  | TextSliceSlice
  | ButtonSliceSlice
  | AccordionSliceSlice;

type TakeactionpageDocumentDataSlices2Slice =
  | EmbedSliceSlice
  | ImageSliceSlice
  | TextSliceSlice
  | ButtonSliceSlice
  | AccordionSliceSlice;

type TakeactionpageDocumentDataSlices3Slice =
  | EmbedSliceSlice
  | ImageSliceSlice
  | TextSliceSlice
  | ButtonSliceSlice
  | AccordionSliceSlice
  | SocialSharerSliceSlice
  | SharePicGallerySliceSlice;

type TakeactionpageDocumentDataSlices4Slice =
  | EmbedSliceSlice
  | ImageSliceSlice
  | TextSliceSlice
  | ButtonSliceSlice
  | AccordionSliceSlice;

/**
 * Content for TakeActionPage documents
 */
interface TakeactionpageDocumentData {
  /**
   * Introduction field in *TakeActionPage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: takeactionpage.introduction
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  introduction: prismic.RichTextField;

  /**
   * SEO Title field in *TakeActionPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: takeactionpage.seo_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_title: prismic.KeyTextField;

  /**
   * SEO Description field in *TakeActionPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: takeactionpage.seo_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_description: prismic.KeyTextField
  /**
   * Slice Zone field in *TakeActionPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: takeactionpage.slices1[]
   * - **Tab**: Pressure
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices1: prismic.SliceZone<TakeactionpageDocumentDataSlices1Slice>
  /**
   * Slice Zone field in *TakeActionPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: takeactionpage.slices2[]
   * - **Tab**: Switch
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices2: prismic.SliceZone<TakeactionpageDocumentDataSlices2Slice>
  /**
   * Slice Zone field in *TakeActionPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: takeactionpage.slices3[]
   * - **Tab**: Share
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices3: prismic.SliceZone<TakeactionpageDocumentDataSlices3Slice>
  /**
   * Slice Zone field in *TakeActionPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: takeactionpage.slices4[]
   * - **Tab**: Learn
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices4: prismic.SliceZone<TakeactionpageDocumentDataSlices4Slice>;
}

/**
 * TakeActionPage document from Prismic
 *
 * - **API ID**: `takeactionpage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TakeactionpageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TakeactionpageDocumentData>,
    "takeactionpage",
    Lang
  >;

type TeampageDocumentDataSlicesSlice = TextSliceSlice;

type TeampageDocumentDataSlices1Slice = TeamMemberSliceSlice;

/**
 * Content for TeamPage documents
 */
interface TeampageDocumentData {
  /**
   * SEO Title field in *TeamPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: teampage.seo_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_title: prismic.KeyTextField;

  /**
   * SEO Description field in *TeamPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: teampage.seo_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_description: prismic.KeyTextField;

  /**
   * Slice Zone field in *TeamPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: teampage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TeampageDocumentDataSlicesSlice>
  /**
   * Slice Zone field in *TeamPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: teampage.slices1[]
   * - **Tab**: teammember
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices1: prismic.SliceZone<TeampageDocumentDataSlices1Slice>;
}

/**
 * TeamPage document from Prismic
 *
 * - **API ID**: `teampage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TeampageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TeampageDocumentData>,
    "teampage",
    Lang
  >;

/**
 * Content for TextOnlyPages documents
 */
interface TextonlypagesDocumentData {
  /**
   * text1 field in *TextOnlyPages*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: textonlypages.text1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text1: prismic.RichTextField;

  /**
   * text2 field in *TextOnlyPages*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: textonlypages.text2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text2: prismic.RichTextField;

  /**
   * text3 field in *TextOnlyPages*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: textonlypages.text3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text3: prismic.RichTextField;

  /**
   * text4 field in *TextOnlyPages*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: textonlypages.text4
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text4: prismic.RichTextField;

  /**
   * text5 field in *TextOnlyPages*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: textonlypages.text5
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text5: prismic.RichTextField;

  /**
   * text6 field in *TextOnlyPages*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: textonlypages.text6
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text6: prismic.RichTextField;
}

/**
 * TextOnlyPages document from Prismic
 *
 * - **API ID**: `textonlypages`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TextonlypagesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TextonlypagesDocumentData>,
    "textonlypages",
    Lang
  >;

type ThankspagesDocumentDataSlicesSlice = ThanksSliceSlice;

/**
 * Content for ThanksPages documents
 */
interface ThankspagesDocumentData {
  /**
   * Slice Zone field in *ThanksPages*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: thankspages.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ThankspagesDocumentDataSlicesSlice>;
}

/**
 * ThanksPages document from Prismic
 *
 * - **API ID**: `thankspages`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ThankspagesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ThankspagesDocumentData>,
    "thankspages",
    Lang
  >;

type ThankspledgeDocumentDataSlicesSlice = SocialSharerSliceSlice;

/**
 * Content for ThanksPledge documents
 */
interface ThankspledgeDocumentData {
  /**
   * title field in *ThanksPledge*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: thankspledge.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * content1 field in *ThanksPledge*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: thankspledge.content1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content1: prismic.RichTextField;

  /**
   * content2 field in *ThanksPledge*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: thankspledge.content2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content2: prismic.RichTextField;

  /**
   * Slice Zone field in *ThanksPledge*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: thankspledge.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ThankspledgeDocumentDataSlicesSlice>;
}

/**
 * ThanksPledge document from Prismic
 *
 * - **API ID**: `thankspledge`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ThankspledgeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ThankspledgeDocumentData>,
    "thankspledge",
    Lang
  >;

type VolunteerspageDocumentDataSlicesSlice = TextSliceSlice;

/**
 * Content for VolunteersPage documents
 */
interface VolunteerspageDocumentData {
  /**
   * SEO Title field in *VolunteersPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: volunteerspage.seo_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_title: prismic.KeyTextField;

  /**
   * SEO Description field in *VolunteersPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: volunteerspage.seo_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_description: prismic.KeyTextField;

  /**
   * Slice Zone field in *VolunteersPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: volunteerspage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<VolunteerspageDocumentDataSlicesSlice>;
}

/**
 * VolunteersPage document from Prismic
 *
 * - **API ID**: `volunteerspage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type VolunteerspageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<VolunteerspageDocumentData>,
    "volunteerspage",
    Lang
  >;

export type AllDocumentTypes =
  | AccordionitemDocument
  | BankpageDocument
  | BlogpostDocument
  | CalltoactionDocument
  | CertificationpageDocument
  | ContactpageDocument
  | DisclaimerpageDocument
  | DonationpageDocument
  | EcobankspageDocument
  | EmbracepageDocument
  | FaqpageDocument
  | HomepageDocument
  | PledgepageDocument
  | PresspageDocument
  | PresspostDocument
  | PrivacypageDocument
  | SfiPageDocument
  | SfipageDocument
  | SwitchsurveyexitDocument
  | TakeactionpageDocument
  | TeampageDocument
  | TextonlypagesDocument
  | ThankspagesDocument
  | ThankspledgeDocument
  | VolunteerspageDocument;

/**
 * Primary content in *AccordionSlice → Primary*
 */
export interface AccordionSliceSliceRichTextPrimary {
  /**
   * Title field in *AccordionSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion_slice.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Content field in *AccordionSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion_slice.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Rich Text variation for AccordionSlice Slice
 *
 * - **API ID**: `richText`
 * - **Description**: AccordionSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AccordionSliceSliceRichText = prismic.SharedSliceVariation<
  "richText",
  Simplify<AccordionSliceSliceRichTextPrimary>,
  never
>;

/**
 * Primary content in *AccordionSlice → Primary*
 */
export interface AccordionSliceSliceRichTextWithStepPrimary {
  /**
   * Title field in *AccordionSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion_slice.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Content field in *AccordionSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion_slice.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Step field in *AccordionSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion_slice.primary.step
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  step: prismic.KeyTextField;
}

/**
 * Rich Text With Step variation for AccordionSlice Slice
 *
 * - **API ID**: `richTextWithStep`
 * - **Description**: AccordionSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AccordionSliceSliceRichTextWithStep = prismic.SharedSliceVariation<
  "richTextWithStep",
  Simplify<AccordionSliceSliceRichTextWithStepPrimary>,
  never
>;

/**
 * Primary content in *AccordionSlice → Primary*
 */
export interface AccordionSliceSliceDefaultPrimary {
  /**
   * ContentLink field in *AccordionSlice → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion_slice.primary.contentlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  contentlink: prismic.ContentRelationshipField;
}

/**
 * Content Link variation for AccordionSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: AccordionSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AccordionSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AccordionSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AccordionSlice*
 */
type AccordionSliceSliceVariation =
  | AccordionSliceSliceRichText
  | AccordionSliceSliceRichTextWithStep
  | AccordionSliceSliceDefault;

/**
 * AccordionSlice Shared Slice
 *
 * - **API ID**: `accordion_slice`
 * - **Description**: AccordionSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AccordionSliceSlice = prismic.SharedSlice<
  "accordion_slice",
  AccordionSliceSliceVariation
>;

/**
 * Primary content in *ButtonSlice → Primary*
 */
export interface ButtonSliceSliceDefaultPrimary {
  /**
   * Label field in *ButtonSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: button_slice.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *ButtonSlice → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: button_slice.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for ButtonSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: ButtonSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ButtonSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ButtonSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ButtonSlice*
 */
type ButtonSliceSliceVariation = ButtonSliceSliceDefault;

/**
 * ButtonSlice Shared Slice
 *
 * - **API ID**: `button_slice`
 * - **Description**: ButtonSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ButtonSliceSlice = prismic.SharedSlice<
  "button_slice",
  ButtonSliceSliceVariation
>;

/**
 * Primary content in *EmbedSlice → Primary*
 */
export interface EmbedSliceSliceDefaultPrimary {
  /**
   * Target field in *EmbedSlice → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: embed_slice.primary.target
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  target: prismic.EmbedField;
}

/**
 * Default variation for EmbedSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: VideoBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EmbedSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EmbedSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *EmbedSlice*
 */
type EmbedSliceSliceVariation = EmbedSliceSliceDefault;

/**
 * EmbedSlice Shared Slice
 *
 * - **API ID**: `embed_slice`
 * - **Description**: VideoBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EmbedSliceSlice = prismic.SharedSlice<
  "embed_slice",
  EmbedSliceSliceVariation
>;

/**
 * Primary content in *FeaturedInSlice → Primary*
 */
export interface FeaturedInSliceSliceDefaultPrimary {
  /**
   * Logo field in *FeaturedInSlice → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_in_slice.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * class field in *FeaturedInSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_in_slice.primary.class
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  class: prismic.KeyTextField;
}

/**
 * Default variation for FeaturedInSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: FeaturedInSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedInSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturedInSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeaturedInSlice*
 */
type FeaturedInSliceSliceVariation = FeaturedInSliceSliceDefault;

/**
 * FeaturedInSlice Shared Slice
 *
 * - **API ID**: `featured_in_slice`
 * - **Description**: FeaturedInSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedInSliceSlice = prismic.SharedSlice<
  "featured_in_slice",
  FeaturedInSliceSliceVariation
>;

/**
 * Primary content in *ImageSlice → Primary*
 */
export interface ImageSliceSliceDefaultPrimary {
  /**
   * Image field in *ImageSlice → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slice.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Caption field in *ImageSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slice.primary.caption
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  caption: prismic.RichTextField;
}

/**
 * Default variation for ImageSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: BlogImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageSlice*
 */
type ImageSliceSliceVariation = ImageSliceSliceDefault;

/**
 * ImageSlice Shared Slice
 *
 * - **API ID**: `image_slice`
 * - **Description**: BlogImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceSlice = prismic.SharedSlice<
  "image_slice",
  ImageSliceSliceVariation
>;

/**
 * Default variation for SharePicGallerySlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: SharePicGallerySlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SharePicGallerySliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *SharePicGallerySlice*
 */
type SharePicGallerySliceSliceVariation = SharePicGallerySliceSliceDefault;

/**
 * SharePicGallerySlice Shared Slice
 *
 * - **API ID**: `share_pic_gallery_slice`
 * - **Description**: SharePicGallerySlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SharePicGallerySliceSlice = prismic.SharedSlice<
  "share_pic_gallery_slice",
  SharePicGallerySliceSliceVariation
>;

/**
 * Primary content in *SocialSharerSlice → Primary*
 */
export interface SocialSharerSliceSliceDefaultPrimary {
  /**
   * text field in *SocialSharerSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: social_sharer_slice.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for SocialSharerSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: SocialSharerSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialSharerSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SocialSharerSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SocialSharerSlice*
 */
type SocialSharerSliceSliceVariation = SocialSharerSliceSliceDefault;

/**
 * SocialSharerSlice Shared Slice
 *
 * - **API ID**: `social_sharer_slice`
 * - **Description**: SocialSharerSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialSharerSliceSlice = prismic.SharedSlice<
  "social_sharer_slice",
  SocialSharerSliceSliceVariation
>;

/**
 * Primary content in *TeamMemberSlice → Primary*
 */
export interface TeamMemberSliceSliceDefaultPrimary {
  /**
   * name field in *TeamMemberSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_member_slice.primary.name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * description field in *TeamMemberSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_member_slice.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * link field in *TeamMemberSlice → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: team_member_slice.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * img field in *TeamMemberSlice → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: team_member_slice.primary.img
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  img: prismic.LinkToMediaField;
}

/**
 * Default variation for TeamMemberSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamMemberSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamMemberSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TeamMemberSlice*
 */
type TeamMemberSliceSliceVariation = TeamMemberSliceSliceDefault;

/**
 * TeamMemberSlice Shared Slice
 *
 * - **API ID**: `team_member_slice`
 * - **Description**: TeamMemberSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamMemberSliceSlice = prismic.SharedSlice<
  "team_member_slice",
  TeamMemberSliceSliceVariation
>;

/**
 * Primary content in *TextSlice → Primary*
 */
export interface TextSliceSliceDefaultPrimary {
  /**
   * Text field in *TextSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_slice.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for TextSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: TextSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextSlice*
 */
type TextSliceSliceVariation = TextSliceSliceDefault;

/**
 * TextSlice Shared Slice
 *
 * - **API ID**: `text_slice`
 * - **Description**: TextSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceSlice = prismic.SharedSlice<
  "text_slice",
  TextSliceSliceVariation
>;

/**
 * Primary content in *ThanksSlice → Primary*
 */
export interface ThanksSliceSliceDefaultPrimary {
  /**
   * title field in *ThanksSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: thanks_slice.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *ThanksSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: thanks_slice.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for ThanksSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ThanksSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ThanksSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ThanksSlice*
 */
type ThanksSliceSliceVariation = ThanksSliceSliceDefault;

/**
 * ThanksSlice Shared Slice
 *
 * - **API ID**: `thanks_slice`
 * - **Description**: ThanksSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ThanksSliceSlice = prismic.SharedSlice<
  "thanks_slice",
  ThanksSliceSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AccordionitemDocument,
      AccordionitemDocumentData,
      BankpageDocument,
      BankpageDocumentData,
      BlogpostDocument,
      BlogpostDocumentData,
      CalltoactionDocument,
      CalltoactionDocumentData,
      CertificationpageDocument,
      CertificationpageDocumentData,
      ContactpageDocument,
      ContactpageDocumentData,
      DisclaimerpageDocument,
      DisclaimerpageDocumentData,
      DonationpageDocument,
      DonationpageDocumentData,
      EcobankspageDocument,
      EcobankspageDocumentData,
      EmbracepageDocument,
      EmbracepageDocumentData,
      FaqpageDocument,
      FaqpageDocumentData,
      HomepageDocument,
      HomepageDocumentData,
      PledgepageDocument,
      PledgepageDocumentData,
      PresspageDocument,
      PresspageDocumentData,
      PresspostDocument,
      PresspostDocumentData,
      PrivacypageDocument,
      PrivacypageDocumentData,
      SfiPageDocument,
      SfiPageDocumentData,
      SfipageDocument,
      SfipageDocumentData,
      SwitchsurveyexitDocument,
      SwitchsurveyexitDocumentData,
      TakeactionpageDocument,
      TakeactionpageDocumentData,
      TeampageDocument,
      TeampageDocumentData,
      TextonlypagesDocument,
      TextonlypagesDocumentData,
      ThankspagesDocument,
      ThankspagesDocumentData,
      ThankspledgeDocument,
      ThankspledgeDocumentData,
      VolunteerspageDocument,
      VolunteerspageDocumentData,
      AllDocumentTypes,
      AccordionSliceSlice,
      AccordionSliceSliceVariation,
      AccordionSliceSliceRichText,
      AccordionSliceSliceRichTextWithStep,
      AccordionSliceSliceDefault,
      ButtonSliceSlice,
      ButtonSliceSliceVariation,
      ButtonSliceSliceDefault,
      EmbedSliceSlice,
      EmbedSliceSliceVariation,
      EmbedSliceSliceDefault,
      FeaturedInSliceSlice,
      FeaturedInSliceSliceVariation,
      FeaturedInSliceSliceDefault,
      ImageSliceSlice,
      ImageSliceSliceVariation,
      ImageSliceSliceDefault,
      SharePicGallerySliceSlice,
      SharePicGallerySliceSliceVariation,
      SharePicGallerySliceSliceDefault,
      SocialSharerSliceSlice,
      SocialSharerSliceSliceVariation,
      SocialSharerSliceSliceDefault,
      TeamMemberSliceSlice,
      TeamMemberSliceSliceVariation,
      TeamMemberSliceSliceDefault,
      TextSliceSlice,
      TextSliceSliceVariation,
      TextSliceSliceDefault,
      ThanksSliceSlice,
      ThanksSliceSliceVariation,
      ThanksSliceSliceDefault,
    };
  }
}
