// Code generated by Slice Machine. DO NOT EDIT.

import AccordionSlice from './AccordionSlice'
import ButtonSlice from './ButtonSlice'
import EmbedSlice from './EmbedSlice'
import FeaturedInSlice from './FeaturedInSlice'
import ImageSlice from './ImageSlice'
import SharePicGallerySlice from './SharePicGallerySlice'
import SocialSharerSlice from './SocialSharerSlice'
import TextSlice from './TextSlice'
import TeamMemberSlice from './TeamMemberSlice'

export {
  AccordionSlice,
  ButtonSlice,
  EmbedSlice,
  FeaturedInSlice,
  ImageSlice,
  SharePicGallerySlice,
  SocialSharerSlice,
  TextSlice,
  TeamMemberSlice
}

export const components = {
  accordion_slice: AccordionSlice,
  button_slice: ButtonSlice,
  embed_slice: EmbedSlice,
  featured_in_slice: FeaturedInSlice,
  image_slice: ImageSlice,
  share_pic_gallery_slice: SharePicGallerySlice,
  social_sharer_slice: SocialSharerSlice,
  text_slice: TextSlice,
  team_member_slice: TeamMemberSlice
}
