query BrandsByCountryQuery($country: String, $state: String) {
  brands(country: $country, displayOnWebsite: true, stateLicensed: $state) {
    edges {
      node {
        name
        tag
        website
        aliases
      }
    }
  }
}

query BrandsQuery(
  $country: String
  $recommendedOnly: Boolean
  $rating: [String]
  $first: Int
) {
  brands(
    country: $country
    recommendedOnly: $recommendedOnly
    rating: $rating
    first: $first
    displayOnWebsite: true
  ) {
    edges {
      node {
        name
        tag
        website
      }
    }
  }
}

query FilteredBrandsQuery(
  $country: String
  $first: Int
  $topPick: Boolean
  $recommendedOnly: Boolean
  $fossilFreeAlliance: Boolean
  $withCommentary: Boolean = false
  $stateLicensed: String
  $harvestData: HarvestDataFilterInput
) {
  brands(
    country: $country
    first: $first
    topPick: $topPick
    recommendedOnly: $recommendedOnly
    fossilFreeAlliance: $fossilFreeAlliance
    stateLicensed: $stateLicensed
    harvestData: $harvestData
  ) {
    edges {
      node {
        name
        tag
        website
        aliases
        commentary @include(if: $withCommentary) {
          ...commentaryFields
        }
        harvestData {
          customersServed
          depositProducts
          financialFeatures
          services
          institutionalInformation
          policies
          loanProducts
          interestRates
        }
      }
    }
  }
}

query BrandByTagQuery($tag: String!) {
  brand(tag: $tag) {
    tag
    name
    website
    commentary {
      lastReviewed
      rating
      ratingInherited
      inheritBrandRating {
        tag
        name
      }
      fossilFreeAlliance
      headline
      description1
      description2
      description3
      subtitle
      institutionType {
        name
      }
      institutionCredentials {
        name
        prismicApiId
      }
    }
    countries {
      code
    }
  }
}

query EmbraceBrandQuery {
  brandsFilteredByEmbraceCampaign(id: 1) {
    name
    website
    tag
  }
}

query AllBanksList {
  brands {
    edges {
      node {
        name
        tag
        commentary {
          showOnSustainableBanksPage
        }
      }
    }
  }
}

fragment commentaryFields on Commentary {
  rating
  ratingInherited
  inheritBrandRating {
    tag
    name
  }
  description3
  lastReviewed
  amountFinancedSince2016
  topPick
  fossilFreeAlliance
  fossilFreeAllianceRating
  showOnSustainableBanksPage
  institutionType {
    name
  }
  institutionCredentials {
    name
    prismicApiId
  }
}

fragment bankFeaturesFields on BrandFeature {
  offered
  feature {
    name
  }
  details
}

query HarvestDataQuery($tag: String!) {
  harvestData(tag: $tag) {
    customersServed
    depositProducts
    financialFeatures
    services
    institutionalInformation
    policies
    loanProducts
    interestRates
  }
}
