const STATE_COUNTIRES = ['US', 'AU', 'CA'] as const;

export type StateCountryCode = (typeof STATE_COUNTIRES)[number];

export const STATE_BY_STATE_CODE = {
  'US-AL': 'Alabama',
  'US-AK': 'Alaska',
  'US-AZ': 'Arizona',
  'US-AR': 'Arkansas',
  'US-CA': 'California',
  'US-CO': 'Colorado',
  'US-CT': 'Connecticut',
  'US-DE': 'Delaware',
  'US-FL': 'Florida',
  'US-GA': 'Georgia',
  'US-HI': 'Hawaii',
  'US-ID': 'Idaho',
  'US-IL': 'Illinois',
  'US-IN': 'Indiana',
  'US-IA': 'Iowa',
  'US-KS': 'Kansas',
  'US-KY': 'Kentucky',
  'US-LA': 'Louisiana',
  'US-ME': 'Maine',
  'US-MD': 'Maryland',
  'US-MA': 'Massachusetts',
  'US-MI': 'Michigan',
  'US-MN': 'Minnesota',
  'US-MS': 'Mississippi',
  'US-MO': 'Missouri',
  'US-MT': 'Montana',
  'US-NE': 'Nebraska',
  'US-NV': 'Nevada',
  'US-NH': 'New Hampshire',
  'US-NJ': 'New Jersey',
  'US-NM': 'New Mexico',
  'US-NY': 'New York',
  'US-NC': 'North Carolina',
  'US-ND': 'North Dakota',
  'US-OH': 'Ohio',
  'US-OK': 'Oklahoma',
  'US-OR': 'Oregon',
  'US-PA': 'Pennsylvania',
  'US-RI': 'Rhode Island',
  'US-SC': 'South Carolina',
  'US-SD': 'South Dakota',
  'US-TN': 'Tennessee',
  'US-TX': 'Texas',
  'US-UT': 'Utah',
  'US-VT': 'Vermont',
  'US-VA': 'Virginia',
  'US-WA': 'Washington',
  'US-WV': 'West Virginia',
  'US-WI': 'Wisconsin',
  'US-WY': 'Wyoming',
  'US-DC': 'District of Columbia',
  'US-AS': 'American Samoa',
  'US-GU': 'Guam',
  'US-MP': 'Northern Mariana Islands',
  'US-PR': 'Puerto Rico',
  'US-UM': 'United States Minor Outlying Islands',
  'US-VI': 'U.S. Virgin Islands',
  'CA-AB': 'Alberta',
  'CA-BC': 'British Columbia',
  'CA-MB': 'Manitoba',
  'CA-NB': 'New Brunswick',
  'CA-NL': 'Newfoundland and Labrador',
  'CA-NS': 'Nova Scotia',
  'CA-NT': 'Northwest Territories',
  'CA-NU': 'Nunavut',
  'CA-ON': 'Ontario',
  'CA-PE': 'Prince Edward Island',
  'CA-QC': 'Quebec',
  'CA-SK': 'Saskatchewan',
  'CA-YT': 'Yukon',
  'AU-ACT': 'Australian Capital Territory',
  'AU-NSW': 'New South Wales',
  'AU-NT': 'Northern Territory',
  'AU-QLD': 'Queensland',
  'AU-SA': 'South Australia',
  'AU-TAS': 'Tasmania',
  'AU-VIC': 'Victoria',
  'AU-WA': 'Western Australia',
} as const;

export type StateCode = keyof typeof STATE_BY_STATE_CODE;

export const STATES_BY_COUNTRY: Record<
  StateCountryCode,
  Record<string, StateCode>
> = {
  US: {
    Alabama: 'US-AL',
    Alaska: 'US-AK',
    Arizona: 'US-AZ',
    Arkansas: 'US-AR',
    California: 'US-CA',
    Colorado: 'US-CO',
    Connecticut: 'US-CT',
    Delaware: 'US-DE',
    Florida: 'US-FL',
    Georgia: 'US-GA',
    Hawaii: 'US-HI',
    Idaho: 'US-ID',
    Illinois: 'US-IL',
    Indiana: 'US-IN',
    Iowa: 'US-IA',
    Kansas: 'US-KS',
    Kentucky: 'US-KY',
    Louisiana: 'US-LA',
    Maine: 'US-ME',
    Maryland: 'US-MD',
    Massachusetts: 'US-MA',
    Michigan: 'US-MI',
    Minnesota: 'US-MN',
    Mississippi: 'US-MS',
    Missouri: 'US-MO',
    Montana: 'US-MT',
    Nebraska: 'US-NE',
    Nevada: 'US-NV',
    'New Hampshire': 'US-NH',
    'New Jersey': 'US-NJ',
    'New Mexico': 'US-NM',
    'New York': 'US-NY',
    'North Carolina': 'US-NC',
    'North Dakota': 'US-ND',
    Ohio: 'US-OH',
    Oklahoma: 'US-OK',
    Oregon: 'US-OR',
    Pennsylvania: 'US-PA',
    'Rhode Island': 'US-RI',
    'South Carolina': 'US-SC',
    'South Dakota': 'US-SD',
    Tennessee: 'US-TN',
    Texas: 'US-TX',
    Utah: 'US-UT',
    Vermont: 'US-VT',
    Virginia: 'US-VA',
    Washington: 'US-WA',
    'West Virginia': 'US-WV',
    Wisconsin: 'US-WI',
    Wyoming: 'US-WY',
    'District of Columbia': 'US-DC',
    'American Samoa': 'US-AS',
    Guam: 'US-GU',
    'Northern Mariana Islands': 'US-MP',
    'Puerto Rico': 'US-PR',
    'United States Minor Outlying Islands': 'US-UM',
    'U.S. Virgin Islands': 'US-VI',
  },
  CA: {
    Alberta: 'CA-AB',
    'British Columbia': 'CA-BC',
    Manitoba: 'CA-MB',
    'New Brunswick': 'CA-NB',
    'Newfoundland and Labrador': 'CA-NL',
    'Nova Scotia': 'CA-NS',
    'Northwest Territories': 'CA-NT',
    Nunavut: 'CA-NU',
    Ontario: 'CA-ON',
    'Prince Edward Island': 'CA-PE',
    Quebec: 'CA-QC',
    Saskatchewan: 'CA-SK',
    Yukon: 'CA-YT',
  },
  AU: {
    'Australian Capital Territory': 'AU-ACT',
    'New South Wales': 'AU-NSW',
    'Northern Territory': 'AU-NT',
    Queensland: 'AU-QLD',
    'South Australia': 'AU-SA',
    Tasmania: 'AU-TAS',
    Victoria: 'AU-VIC',
    'Western Australia': 'AU-WA',
  },
} as const;

export const isValidStateCountry = (
  country: unknown
): country is StateCountryCode =>
  typeof country === 'string' &&
  STATE_COUNTIRES.includes(country as StateCountryCode);
