name: Build and Deploy Stage

on:
  push:
    branches: [stage]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      NUXT_APP_ENV: development
      NUXT_IMAGE_PROVIDER: prismic
      PUBLIC_DOMAIN_URL: https://test.bank.green
      NUXT_PUBLIC_CLOUDFLARE_CAPTCHA_SITEKEY: ${{ secrets.CAPTCHA_SITEKEY }}
      NUXT_PUBLIC_CLOUDFLARE_CAPTCHA_SECRET: ${{ secrets.CAPTCHA_SECRET}}
      PUBLIC_EMBRACE_URL: https://embrace-django.bank.green/api
      ZAPIER_CONTACT: ${{ secrets.ZAPIER_CONTACT }}
      ZAPIER_OTHER_SUBMIT: ${{ secrets.ZAPIER_OTHER_SUBMIT }}
      NUXT_PUBLIC_ACTIVE_CAMPAIGN_API_KEY: ${{ secrets.ACTIVE_CAMPAIGN_KEY }}
      NUXT_PUBLIC_ACTIVE_CAMPAIGN_URL: ${{ secrets.ACTIVE_CAMPAIGN_URL }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"
      - run: npm ci
      - run: npm i -g wrangler
      - run: npm run build
      - run: npm run deploy
      - uses: schnerring/cloudflare-pages-branch-alias-action@v1
        id: pages-branch-alias
        with:
          # git-branch input
          git-branch: ${{ github.ref_name }}

      - name: Build Stage Alias
        # branch-alias output
        run: |
          hugo \
            --minify \
            --baseURL "https://${{ steps.pages-branch-alias.outputs.branch-alias }}.website-staging.bank-green.workers.dev"
