name: Linting for staged files
run-name: Run ESLint in staged files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Prepare Nuxt
        run: npm run prepare
        
      - name: Run linter
        run: npm run lint-staged